name: Create Fox Eggs Keystore

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore FoxEggs.keystore \
            -alias foxeggs \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass Mani3840494915Mani \
            -keypass Mani3840494915Mani \
            -dname "CN=Fox Eggs, O=Fox Eggs, C=AZ"

      - name: Convert to Base64
        run: |
          base64 -w 0 FoxEggs.keystore > KEYSTORE_BASE64.txt

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FoxEggs-Keystore
          path: KEYSTORE_BASE64.txt
